spring.application.name=BBJ
application.version=1.0.0
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/gusgo
spring.datasource.username=gusgo
spring.datasource.password=gusgo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
logging.level.liquibase=DEBUG

spring.security.oauth2.resourceserver.jwt.public-key=classpath:certs/public.pem
spring.security.oauth2.resourceserver.jwt.private-key=classpath:certs/private.pem